# backend/neet_app/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenRefreshView, TokenBlacklistView
from .views import (
    TopicViewSet, QuestionViewSet, TestSessionViewSet, TestAnswerViewSet,
    StudentProfileViewSet, ReviewCommentViewSet,
    dashboard_analytics, dashboard_comprehensive_analytics, 
    sync_neo4j_to_postgresql, reset_chapter_structure, sync_questions_from_neo4j
)
from .views.test_views import (
    create_test_student, test_login, test_topic_classification,
    create_test_session, system_status
)
from .authentication import StudentTokenObtainPairView

# Initialize DefaultRouter with default trailing_slash behavior (True)
# This will make all URLs generated by this router have a trailing slash
router = DefaultRouter()
router.register(r'topics', TopicViewSet, basename='topic')
router.register(r'questions', QuestionViewSet, basename='question')
router.register(r'test-sessions', TestSessionViewSet, basename='test-session')
router.register(r'test-answers', TestAnswerViewSet, basename='test-answer')
router.register(r'student-profile', StudentProfileViewSet, basename='student-profile')
router.register(r'students', StudentProfileViewSet, basename='students')  # For /students/me/ endpoint
router.register(r'review-comments', ReviewCommentViewSet, basename='review-comment')


urlpatterns = [
    path('', include(router.urls)),
    path('topics/delete-all/', TopicViewSet.as_view({'delete': 'delete_all'}), name='topics-delete-all'),
    
    # JWT Authentication endpoints
    path('auth/login/', StudentTokenObtainPairView.as_view(), name='student-token-obtain-pair'),
    path('auth/refresh/', TokenRefreshView.as_view(), name='token-refresh'),
    path('auth/logout/', TokenBlacklistView.as_view(), name='token-blacklist'),
    
    # Dashboard endpoints
    path('dashboard/analytics/', dashboard_analytics, name='dashboard-analytics'),
    path('dashboard/reset-chapter-structure/', reset_chapter_structure, name='reset-chapter-structure'),
    path('dashboard/sync-neo4j-to-postgresql/', sync_neo4j_to_postgresql, name='sync-neo4j-to-postgresql'),
    path('dashboard/comprehensive-analytics/', dashboard_comprehensive_analytics, name='dashboard-comprehensive-analytics'),
    path('dashboard/sync-questions-from-neo4j/', sync_questions_from_neo4j, name='sync-questions-from-neo4j'),
    
    # Test endpoints for new authentication system
    path('test/create-student/', create_test_student, name='test-create-student'),
    path('test/login/', test_login, name='test-login'),
    path('test/classify-topics/', test_topic_classification, name='test-classify-topics'),
    path('test/create-session/', create_test_session, name='test-create-session'),
    path('test/status/', system_status, name='test-status'),
]