# backend/neet_app/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenRefreshView, TokenBlacklistView
from .views import (
    TopicViewSet, QuestionViewSet, TestSessionViewSet, TestAnswerViewSet,
    StudentProfileViewSet, ReviewCommentViewSet, TimeTrackingViewSet,
    ChatSessionViewSet, chat_statistics,
    dashboard_analytics, dashboard_comprehensive_analytics
)
from .views.utils import (
    clean_existing_questions, sync_topics_from_database_question, 
    sync_questions_from_database_question, sync_all_from_database_question,
    reset_questions_and_topics
)
from .views.test_views import (
    create_test_student, test_login, test_topic_classification,
    create_test_session, system_status
)
from .views.insights_views import (
    get_student_insights, get_topic_details, get_insights_config, get_insights_cache
)
from .authentication import StudentTokenObtainPairView

# Initialize DefaultRouter with default trailing_slash behavior (True)
# This will make all URLs generated by this router have a trailing slash
router = DefaultRouter()
router.register(r'topics', TopicViewSet, basename='topic')
router.register(r'questions', QuestionViewSet, basename='question')
router.register(r'test-sessions', TestSessionViewSet, basename='test-session')
router.register(r'test-answers', TestAnswerViewSet, basename='test-answer')
router.register(r'student-profile', StudentProfileViewSet, basename='student-profile')
router.register(r'students', StudentProfileViewSet, basename='students')  # For /students/me/ endpoint
router.register(r'review-comments', ReviewCommentViewSet, basename='review-comment')
router.register(r'time-tracking', TimeTrackingViewSet, basename='time-tracking')
router.register(r'chat-sessions', ChatSessionViewSet, basename='chat-session')


urlpatterns = [
    path('', include(router.urls)),
    path('topics/delete-all/', TopicViewSet.as_view({'delete': 'delete_all'}), name='topics-delete-all'),
    
    # JWT Authentication endpoints
    path('auth/login/', StudentTokenObtainPairView.as_view(), name='student-token-obtain-pair'),
    path('auth/refresh/', TokenRefreshView.as_view(), name='token-refresh'),
    path('auth/logout/', TokenBlacklistView.as_view(), name='token-blacklist'),
    
    # Chatbot endpoints (additional to router)
    path('chatbot/statistics/', chat_statistics, name='chat-statistics'),
    
    # Dashboard endpoints
    path('dashboard/analytics/', dashboard_analytics, name='dashboard-analytics'),
    path('dashboard/comprehensive-analytics/', dashboard_comprehensive_analytics, name='dashboard-comprehensive-analytics'),
    
    # PostgreSQL-based sync endpoints (new)
    path('dashboard/sync-topics/', sync_topics_from_database_question, name='sync-topics-from-database-question'),
    path('dashboard/sync-questions/', sync_questions_from_database_question, name='sync-questions-from-database-question'),
    path('dashboard/sync-all/', sync_all_from_database_question, name='sync-all-from-database-question'),
    path('dashboard/reset-data/', reset_questions_and_topics, name='reset-questions-and-topics'),
    path('dashboard/clean-existing-questions/', clean_existing_questions, name='clean-existing-questions'),
    
    # Test endpoints for new authentication system
    path('test/create-student/', create_test_student, name='test-create-student'),
    path('test/login/', test_login, name='test-login'),
    path('test/classify-topics/', test_topic_classification, name='test-classify-topics'),
    path('test/create-session/', create_test_session, name='test-create-session'),
    path('test/status/', system_status, name='test-status'),
    
    # Insights endpoints for student performance analysis
    path('insights/student/', get_student_insights, name='student-insights'),
    path('insights/cache/', get_insights_cache, name='insights-cache'),
    path('insights/topics/', get_topic_details, name='topic-details'),
    path('insights/config/', get_insights_config, name='insights-config'),
]