# Generated by Django 5.2.4 on 2025-08-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("neet_app", "0002_studentinsight_testanswer_visit_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="auth_provider",
            field=models.CharField(
                choices=[("local", "Local"), ("google", "Google"), ("both", "Both")],
                default="local",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="google_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="google_picture",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="google_sub",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["google_sub"], name="student_pro_google__44ed63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["google_email"], name="student_pro_google__278dab_idx"
            ),
        ),
    ]
