# Generated by Django 5.2.4 on 2025-07-31 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("neet_app", "0002_alter_studentprofile_generated_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("student_id", models.CharField(db_index=True, max_length=20)),
                (
                    "chat_session_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("session_title", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Chat Session",
                "verbose_name_plural": "Chat Sessions",
                "db_table": "chat_sessions",
                "indexes": [
                    models.Index(
                        fields=["student_id", "created_at"],
                        name="chat_sessio_student_2db1d4_idx",
                    ),
                    models.Index(
                        fields=["is_active", "updated_at"],
                        name="chat_sessio_is_acti_aebe78_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "message_type",
                    models.CharField(
                        choices=[("user", "User"), ("bot", "Bot")], max_length=10
                    ),
                ),
                ("message_content", models.TextField()),
                ("sql_query", models.TextField(blank=True, null=True)),
                ("processing_time", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat_session",
                    models.ForeignKey(
                        db_column="chat_session_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="neet_app.chatsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "db_table": "chat_messages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["chat_session", "created_at"],
                        name="chat_messag_chat_se_b79339_idx",
                    ),
                    models.Index(
                        fields=["message_type", "created_at"],
                        name="chat_messag_message_977880_idx",
                    ),
                ],
            },
        ),
    ]
