# Generated by Django 5.2.4 on 2025-08-29 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("neet_app", "0003_studentprofile_auth_provider_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="password_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PasswordReset",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "reset_token_hash",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neet_app.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Reset",
                "verbose_name_plural": "Password Resets",
                "db_table": "password_resets",
                "indexes": [
                    models.Index(
                        fields=["user", "expires_at"],
                        name="password_re_user_id_dfecd9_idx",
                    ),
                    models.Index(
                        fields=["reset_token_hash"],
                        name="password_re_reset_t_058bc5_idx",
                    ),
                ],
            },
        ),
    ]
