# Generated by Django 5.2.4 on 2025-08-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("neet_app", "0003_chatsession_chatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatabaseQuestion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("question_number", models.IntegerField(blank=True, null=True)),
                ("question_text", models.TextField(blank=True, null=True)),
                ("question_type", models.TextField(blank=True, null=True)),
                ("option_1", models.TextField(blank=True, null=True)),
                ("option_2", models.TextField(blank=True, null=True)),
                ("option_3", models.TextField(blank=True, null=True)),
                ("option_4", models.TextField(blank=True, null=True)),
                ("subject", models.TextField(blank=True, null=True)),
                ("chapter", models.TextField(blank=True, null=True)),
                ("topic", models.TextField(blank=True, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("source", models.TextField(blank=True, null=True)),
                ("source_page", models.IntegerField(blank=True, null=True)),
                ("correct_answer", models.TextField(blank=True, null=True)),
                ("explanation", models.TextField(blank=True, null=True)),
                ("difficulty", models.TextField(blank=True, null=True)),
                ("explanation_image", models.TextField(blank=True, null=True)),
                ("option_1_image", models.TextField(blank=True, null=True)),
                ("option_2_image", models.TextField(blank=True, null=True)),
                ("option_3_image", models.TextField(blank=True, null=True)),
                ("option_4_image", models.TextField(blank=True, null=True)),
                ("question_image", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Database Question",
                "verbose_name_plural": "Database Questions",
                "db_table": "database_question",
            },
        ),
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={
                ("question", "topic", "option_a", "option_b", "option_c", "option_d")
            },
        ),
        migrations.AlterUniqueTogether(
            name="topic",
            unique_together={("name", "subject", "chapter")},
        ),
    ]
