# Generated by Django 5.2.4 on 2025-09-01 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("neet_app", "0004_studentprofile_password_changed_at_passwordreset"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("notification_type", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("sent", "sent"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
            },
        ),
        migrations.AddField(
            model_name="platformtest",
            name="scheduled_date_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="platformtest",
            index=models.Index(
                fields=["scheduled_date_time"], name="platform_te_schedul_2b0a89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="platformtest",
            index=models.Index(
                fields=["is_active", "scheduled_date_time"],
                name="platform_te_is_acti_7cbbec_idx",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_column="user_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="neet_app.studentprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "notification_type", "status", "created_at"],
                name="notificatio_user_id_57edf3_idx",
            ),
        ),
    ]
