# Generated by Django 5.2.4 on 2025-09-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neet_app', '0005_notification_platformtest_scheduled_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformtest',
            name='difficulty_distribution',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
