# Generated by Django 5.2.4 on 2025-09-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neet_app', '0007_testsession_is_active_testsession_last_heartbeat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAdminAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
