# Generated by Django 5.2.4 on 2025-09-15 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neet_app", "0010_studentactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="subscription_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="subscription_plan",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="RazorpayOrder",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("plan", models.CharField(max_length=50)),
                ("amount", models.IntegerField(help_text="Amount in paise")),
                ("currency", models.CharField(default="INR", max_length=10)),
                (
                    "razorpay_order_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "razorpay_signature",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("status", models.CharField(default="created", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="razorpay_orders",
                        to="neet_app.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "razorpay_orders",
            },
        ),
    ]
