# Generated by Django 5.2.4 on 2025-09-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neet_app", "0011_studentprofile_subscription_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="razorpayorder",
            name="status",
            field=models.CharField(
                default="created",
                help_text="Order status: initiated | created | paid | failed | remote_failed",
                max_length=32,
            ),
        ),
    ]
