# Generated by Django 5.2.4 on 2025-09-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neet_app", "0012_alter_razorpayorder_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="auth_provider",
            field=models.CharField(
                choices=[
                    ("local", "Local"),
                    ("google", "Google"),
                    ("mobile", "Mobile"),
                    ("both", "Both"),
                ],
                default="local",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="full_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
