# Generated by Django 5.2.4 on 2025-09-26 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neet_app", "0013_alter_studentprofile_auth_provider_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMemory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "memory_type",
                    models.CharField(
                        choices=[
                            ("long_term", "Long Term"),
                            ("short_term", "Short Term"),
                        ],
                        default="long_term",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        default=dict,
                        help_text="Structured memory content with facts, tags, and metadata",
                    ),
                ),
                (
                    "source_session_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "key_tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags for categorizing memories (subjects, topics, etc.)",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=1.0, help_text="Confidence in memory accuracy (0.0-1.0)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_memories",
                        to="neet_app.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Memory",
                "verbose_name_plural": "Chat Memories",
                "db_table": "chat_memory",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "memory_type"],
                        name="chat_memory_student_2b1090_idx",
                    ),
                    models.Index(
                        fields=["source_session_id"],
                        name="chat_memory_source__b8185d_idx",
                    ),
                    models.Index(
                        fields=["memory_type", "updated_at"],
                        name="chat_memory_memory__4ebd96_idx",
                    ),
                    models.Index(
                        fields=["student", "memory_type", "confidence_score"],
                        name="chat_memory_student_80040a_idx",
                    ),
                ],
            },
        ),
    ]
