# Generated by Django 5.2.4 on 2025-11-06 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neet_app", "0014_chatmemory"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionAdmin",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Institution Admin",
                "verbose_name_plural": "Institution Admins",
                "db_table": "institution_admins",
            },
        ),
        migrations.AddField(
            model_name="platformtest",
            name="exam_type",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="platformtest",
            name="is_institution_test",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="question",
            name="exam_type",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="institution_test_name",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("exam_types", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Institution",
                "verbose_name_plural": "Institutions",
                "db_table": "institutions",
                "indexes": [
                    models.Index(fields=["code"], name="institution_code_676f96_idx"),
                    models.Index(
                        fields=["is_active", "created_at"],
                        name="institution_is_acti_faa344_idx",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="platformtest",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="neet_app.institution",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="neet_app.institution",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="neet_app.institution",
            ),
        ),
        migrations.AddIndex(
            model_name="platformtest",
            index=models.Index(
                fields=["institution", "is_institution_test"],
                name="platform_te_institu_15da77_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="platformtest",
            index=models.Index(
                fields=["institution", "exam_type", "is_active"],
                name="platform_te_institu_43cf41_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["institution", "institution_test_name"],
                name="questions_institu_a0f9a6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["institution", "exam_type"], name="questions_institu_792d1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["institution"], name="student_pro_institu_ffbe2c_idx"
            ),
        ),
        migrations.AddField(
            model_name="institutionadmin",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admins",
                to="neet_app.institution",
            ),
        ),
        migrations.AddIndex(
            model_name="institutionadmin",
            index=models.Index(
                fields=["username"], name="institution_usernam_479610_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="institutionadmin",
            index=models.Index(
                fields=["institution", "is_active"],
                name="institution_institu_f148f7_idx",
            ),
        ),
    ]
