# Generated by Django 5.2.4 on 2025-11-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neet_app", "0015_institutionadmin_platformtest_exam_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="explanation_image",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="option_a_image",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="option_b_image",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="option_c_image",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="option_d_image",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="question_image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
