# Generated by Django 5.2.4 on 2025-11-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "neet_app",
            "0016_question_explanation_image_question_option_a_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="testanswer",
            name="text_answer",
            field=models.TextField(
                blank=True,
                help_text="Descriptive answer for NVT questions (numeric, string, or decimal)",
                null=True,
            ),
        ),
    ]
