# Generated by Django 5.2.4 on 2025-11-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neet_app", "0017_testanswer_text_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsession",
            name="math_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testsession",
            name="math_topics",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={
                (
                    "question",
                    "topic",
                    "option_a",
                    "option_b",
                    "option_c",
                    "option_d",
                    "institution",
                    "institution_test_name",
                )
            },
        ),
    ]
