# Generated by Django 5.2.4 on 2025-11-11 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neet_app", "0018_testsession_math_score_testsession_math_topics_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestSubjectZoneInsight",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("subject", models.CharField(max_length=20)),
                ("steady_zone", models.JSONField(blank=True, default=list)),
                ("edge_zone", models.JSONField(blank=True, default=list)),
                ("focus_zone", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("questions_analyzed", models.JSONField(blank=True, default=list)),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zone_insights",
                        to="neet_app.studentprofile",
                    ),
                ),
                (
                    "test_session",
                    models.ForeignKey(
                        db_column="test_session_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zone_insights",
                        to="neet_app.testsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Subject Zone Insight",
                "verbose_name_plural": "Test Subject Zone Insights",
                "db_table": "test_subject_zone_insights",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "test_session"],
                        name="test_subjec_student_7ece2e_idx",
                    ),
                    models.Index(
                        fields=["test_session", "subject"],
                        name="test_subjec_test_se_299d05_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="test_subjec_created_a60c19_idx"
                    ),
                ],
                "unique_together": {("test_session", "subject")},
            },
        ),
    ]
