# Generated by Django 5.2.4 on 2025-11-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neet_app", "0019_testsubjectzoneinsight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.TextField(
                blank=True,
                help_text="Correct answer: single-letter for MCQ or numeric/text for NVT",
                null=True,
            ),
        ),
    ]
