# Generated by Django 5.2.4 on 2025-11-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neet_app", "0020_alter_question_correct_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="institution_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="is_institution_student",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["institution_code"], name="student_pro_institu_069a54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["is_institution_student"], name="student_pro_is_inst_244fd6_idx"
            ),
        ),
    ]
