# Generated by Django 5.2.4 on 2025-11-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neet_app", "0021_studentprofile_institution_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsession",
            name="biology_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testsession",
            name="biology_topics",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
