# Generated by Django 5.2.4 on 2025-11-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neet_app", "0022_testsession_biology_score_testsession_biology_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformtest",
            name="expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
