# Generated by Django 5.2.4 on 2026-01-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neet_app", "0023_platformtest_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="misconceptions",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text='JSON mapping of wrong options to misconceptions: {"option_a": "misconception text", ...}',
                null=True,
            ),
        ),
    ]
