# Generated by Django 5.2.4 on 2026-01-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neet_app", "0024_question_misconceptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformtest",
            name="misconception_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="platformtest",
            name="misconception_generation_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
                null=True,
            ),
        ),
    ]
