# Generated by Django 5.2.4 on 2026-02-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neet_app", "0025_platformtest_misconception_generated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="razorpayorder",
            name="amount",
            field=models.IntegerField(help_text="Amount in rupees"),
        ),
    ]
