# Generated by Django 5.2.4 on 2026-02-03 05:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("neet_app", "0026_alter_razorpayorder_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testsubjectzoneinsight",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Test Subject Checkpoint",
                "verbose_name_plural": "Test Subject Checkpoints",
            },
        ),
        migrations.RenameField(
            model_name="testsubjectzoneinsight",
            old_name="edge_zone",
            new_name="checkpoints",
        ),
        migrations.RenameField(
            model_name="testsubjectzoneinsight",
            old_name="focus_zone",
            new_name="topics_analyzed",
        ),
        migrations.RemoveField(
            model_name="testsubjectzoneinsight",
            name="questions_analyzed",
        ),
        migrations.RemoveField(
            model_name="testsubjectzoneinsight",
            name="steady_zone",
        ),
    ]
