# Generated by Django 5.2.4 on 2026-02-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neet_app", "0027_alter_testsubjectzoneinsight_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="is_first_login",
            field=models.BooleanField(default=True),
        ),
    ]
