# Generated by Django 5.2.4 on 2026-02-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neet_app", "0028_studentprofile_is_first_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsession",
            name="insights_audio_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
