# Generated by Django 5.2.4 on 2026-02-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neet_app", "0029_testsession_insights_audio_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="testanswer",
            name="is_bookmarked",
            field=models.BooleanField(default=False),
        ),
    ]
