# Generated by Django 5.2.4 on 2026-02-15 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neet_app", "0030_testanswer_is_bookmarked"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentOrder",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "provider",
                    models.CharField(
                        choices=[("razorpay", "Razorpay"), ("play", "Google Play")],
                        db_index=True,
                        default="razorpay",
                        help_text="Payment provider: razorpay or play",
                        max_length=20,
                    ),
                ),
                ("plan", models.CharField(max_length=50)),
                ("amount", models.IntegerField(help_text="Amount in rupees")),
                ("currency", models.CharField(default="INR", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("created", "Created"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("remote_failed", "Remote Failed"),
                        ],
                        default="created",
                        help_text="Order status",
                        max_length=32,
                    ),
                ),
                (
                    "razorpay_order_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                (
                    "razorpay_signature",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "play_purchase_token",
                    models.TextField(
                        blank=True,
                        db_index=True,
                        help_text="Google Play purchase token",
                        null=True,
                    ),
                ),
                (
                    "play_product_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Play product/SKU ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "play_order_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Play order ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_orders",
                        to="neet_app.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "payment_orders",
            },
        ),
        migrations.DeleteModel(
            name="RazorpayOrder",
        ),
        migrations.AddIndex(
            model_name="paymentorder",
            index=models.Index(
                fields=["student", "provider", "status"],
                name="payment_ord_student_b1d30c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentorder",
            index=models.Index(
                fields=["provider", "created_at"], name="payment_ord_provide_937baf_idx"
            ),
        ),
    ]
