# Generated by Django 5.2.4 on 2026-02-20 10:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("neet_app", "0031_paymentorder_delete_razorpayorder_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentInsight",
        ),
    ]
