# Generated by Django 5.2.4 on 2026-02-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neet_app", "0032_delete_studentinsight"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="testsubjectzoneinsight",
            name="test_subjec_test_se_299d05_idx",
        ),
        migrations.AlterUniqueTogether(
            name="testsubjectzoneinsight",
            unique_together={("test_session", "student")},
        ),
        migrations.AddField(
            model_name="testsubjectzoneinsight",
            name="accuracy",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testsubjectzoneinsight",
            name="focus_zone",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="testsubjectzoneinsight",
            name="g_phrase",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testsubjectzoneinsight",
            name="mark",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testsubjectzoneinsight",
            name="repeated_mistake",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="testsubjectzoneinsight",
            name="subject_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="testsubjectzoneinsight",
            name="time_spend",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="testsubjectzoneinsight",
            name="total_mark",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="testsubjectzoneinsight",
            name="subject",
        ),
    ]
