# Generated by Django 5.2.4 on 2026-02-22 10:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "neet_app",
            "0033_remove_testsubjectzoneinsight_test_subjec_test_se_299d05_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionOfTheDay",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "selected_option",
                    models.CharField(
                        blank=True,
                        help_text="Selected answer: A, B, C, or D",
                        max_length=1,
                        null=True,
                    ),
                ),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neet_app.question",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neet_app.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question of the Day",
                "verbose_name_plural": "Questions of the Day",
                "db_table": "question_of_the_day",
                "indexes": [
                    models.Index(
                        fields=["student", "date"],
                        name="question_of_student_33c515_idx",
                    ),
                    models.Index(fields=["date"], name="question_of_date_d2d212_idx"),
                ],
                "unique_together": {("student", "date")},
            },
        ),
    ]
