# Generated by Django 5.2.4 on 2026-02-28 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neet_app", "0034_questionoftheday"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionFeedback",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("INCORRECT_QUESTION", "Incorrect Question"),
                            ("OUT_OF_SYLLABUS", "Out of Syllabus"),
                            ("OPTIONS_INCORRECT", "Options are Incorrect"),
                            ("QUESTION_UNCLEAR", "Question is Unclear"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neet_app.question",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neet_app.studentprofile",
                    ),
                ),
                (
                    "test_session",
                    models.ForeignKey(
                        db_column="test_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neet_app.testsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Feedback",
                "verbose_name_plural": "Question Feedback",
                "db_table": "question_feedback",
                "indexes": [
                    models.Index(
                        fields=["student", "created_at"],
                        name="question_fe_student_e27b40_idx",
                    ),
                    models.Index(
                        fields=["test_session", "created_at"],
                        name="question_fe_test_id_34bf95_idx",
                    ),
                    models.Index(
                        fields=["question", "feedback_type"],
                        name="question_fe_questio_334e6f_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="question_fe_created_e6e350_idx"
                    ),
                ],
                "unique_together": {("student", "test_session", "question")},
            },
        ),
    ]
