# Generated by Django 5.2.4 on 2026-03-02 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neet_app", "0035_questionfeedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testsession",
            name="test_type",
            field=models.CharField(
                choices=[
                    ("custom", "Custom Test"),
                    ("platform", "Platform Test"),
                    ("pyq", "Previous Year Question Paper"),
                ],
                default="custom",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PreviousYearQuestionPaper",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("source_filename", models.TextField()),
                ("question_count", models.IntegerField(default=0)),
                (
                    "exam_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pyq_papers",
                        to="neet_app.institution",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_pyqs",
                        to="neet_app.institutionadmin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Previous Year Question Paper",
                "verbose_name_plural": "Previous Year Question Papers",
                "db_table": "previous_year_question_papers",
                "indexes": [
                    models.Index(
                        fields=["institution", "is_active"],
                        name="previous_ye_institu_b3cfec_idx",
                    ),
                    models.Index(
                        fields=["exam_type", "is_active"],
                        name="previous_ye_exam_ty_0c89ac_idx",
                    ),
                    models.Index(
                        fields=["-uploaded_at"], name="previous_ye_uploade_57b9c2_idx"
                    ),
                ],
                "unique_together": {("institution", "name")},
            },
        ),
    ]
