# Generated by Django 5.2.4 on 2026-03-03 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neet_app", "0036_alter_testsession_test_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionfeedback",
            name="question",
            field=models.ForeignKey(
                blank=True,
                db_column="question_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="neet_app.question",
            ),
        ),
        migrations.AlterField(
            model_name="questionoftheday",
            name="question",
            field=models.ForeignKey(
                blank=True,
                db_column="question_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="neet_app.question",
            ),
        ),
        migrations.AlterField(
            model_name="reviewcomment",
            name="question",
            field=models.ForeignKey(
                db_column="question_id",
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="neet_app.question",
            ),
        ),
        migrations.AlterField(
            model_name="testanswer",
            name="question",
            field=models.ForeignKey(
                db_column="question_id",
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="neet_app.question",
            ),
        ),
    ]
